security:      
#    encoders:
#        Symfony\Component\Security\Core\User\User:
#            algorithm:  sha1
#            iterations: 1
#            encode_as_base64: true
#        Taller\AeronauticoBundle\Entity\Usuario: sha512

    firewalls:
 #       login_firewall:
 #           pattern:    ^/login$
 #           anonymous: true
        assets:
            pattern:  ^/(_(profiler|wdt)|css|images|js|favicon.ico)/
            security: false   
        principal:
            pattern:    ^/
            form_login: 
                provider: fos_userbundle
            logout:       true
            anonymous:    true
# para lo opcion de recordarlo mas tiempo si tilda la opcion rememberme
            remember_me:
              key:      Cla,ve_ScrimorP?"
              lifetime: 3600
              path:     /
              domain:   ~ # Defaults to the current domain from $_SERVER
            
    access_control:
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, role: ROLE_USER }
#         - { path: ^/, roles: ROLE_USER }      
#         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
           
    providers:
        fos_userbundle:
            id: fos_user.user_manager
            
 #   encoders:
 #           Taller\AeronauticoBundle\Entity\Usuario: 
  #            algorithm: sha512
   #           encode-as-base64: true
    #          iterations: 5
                  #id: fos_user.user_manager       
#        Taller\AeronauticoBundle\Entity\Usuario: sha512
#        Taller\AeronauticoBundle\Entity\Usuario: plaintext
#        Taller\AeronauticoBundle\Entity\Usuario:
#            algorithm: sha512
#            encode-as-base64: true
#            iterations: 5

#        id: fos_user.user_manager       
