parameters:
#    aeronautico.example.class: Taller\AeronauticoBundle\Example

services:
#    aeronautico.example:
#        class: %aeronautico.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
