Status:
  type: entity
  table: status
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nombre:
      type: string
      length: 20
      fixed: false
      nullable: false
    tabla:
      type: string
      length: 20
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
